"""
Conversation memory for the AI Analyst: a compact structured state per chat session, and a
deterministic resolver for follow-ups ("make this a chart", "what about February?", "now spend").

    session id (opaque, generated by the browser) -> SessionState: the last analytical request as a
    validated query_planner.Plan, plus a little metadata. No transcript, no answers, no personal text.

Follow-ups are resolved by editing the remembered plan (metric, entity, filter, period, chart type),
re-validating it with query_planner.validate_plan() and running it on the data tools: 0 LLM calls.
Only a follow-up this can't resolve goes to the analytics planner, with the compact previous plan
(never the transcript). A reference with nothing to refer to gets a clarification.

Sessions live in this process's memory, bounded in number and age: a server restart (e.g. a Render
redeploy or cold start) forgets them, and the conversation simply starts fresh.
"""
import copy
import json
import re
import threading
import time
from collections import OrderedDict, deque
from dataclasses import dataclass, field

import chart_builder as cb
import query_planner as qp
import query_router as qr

SESSION_ID_RE = re.compile(r"^[A-Za-z0-9-]{16,64}$")
MAX_SESSIONS = 2000
SESSION_TTL_S = 4 * 3600
MAX_TURNS = 6


@dataclass
class SessionState:
    plan: qp.Plan = None        # the last analytical request, validated
    question: str = None        # its wording (truncated); only analytical requests are kept
    route: str = None
    chart: dict = None          # {"type", "title"} of the last chart, no data
    turns: deque = field(default_factory=lambda: deque(maxlen=MAX_TURNS))  # {"route", "kind"}: no text
    updated: float = 0.0

    def remember(self, plan, question: str, route: str, chart: dict = None):
        self.plan, self.question, self.route = plan, (question or "")[:200], route
        self.chart = {"type": chart["type"], "title": chart["title"]} if chart else None


class SessionStore:
    """In-process, bounded (least recently used sessions are dropped first) and time-limited."""

    def __init__(self, max_sessions: int = MAX_SESSIONS, ttl_s: float = SESSION_TTL_S, clock=time.monotonic):
        self.max_sessions, self.ttl_s, self._clock = max_sessions, ttl_s, clock
        self._sessions = OrderedDict()
        self._lock = threading.Lock()

    def get(self, session_id):
        """The session's state (created on first use), or None for a missing/invalid id."""
        if not isinstance(session_id, str) or not SESSION_ID_RE.match(session_id):
            return None
        with self._lock:
            now = self._clock()
            while self._sessions:
                oldest = next(iter(self._sessions.values()))
                if now - oldest.updated <= self.ttl_s:
                    break
                self._sessions.popitem(last=False)
            state = self._sessions.pop(session_id, None) or SessionState()
            state.updated = now
            self._sessions[session_id] = state
            while len(self._sessions) > self.max_sessions:
                self._sessions.popitem(last=False)
            return state

    def __len__(self):
        return len(self._sessions)


# ---------------------------------------------------------------------------
# Small talk and out-of-scope personal topics (answered here, 0 LLM calls, nothing remembered)
# ---------------------------------------------------------------------------

_c = lambda p: re.compile(p, re.IGNORECASE)  # noqa: E731
GREETING_RE = _c(r"^\W*(?:hi|hello|hey|hiya|howdy|greetings|good (?:morning|afternoon|evening))"
                 r"(?:\s+(?:there|team|again|marketingiq))?\W*$")
THANKS_RE = _c(r"^\W*(?:thanks?(?: you)?(?: so much| a lot| very much)?|thank you(?: so much| very much)?|ty|cheers"
               r"|great|awesome|perfect|cool|nice|ok(?:ay)?|got it|excellent|amazing|brilliant|wonderful)"
               r"(?:\W+(?:thanks?|thank you))?\W*$")
IDENTITY_RE = _c(r"^\W*(?:who are you|what are you|what (?:can|do) you do|what (?:can|could) you help(?: me)?(?: with)?"
                 r"|how (?:can|could|do) you help(?: me)?|help(?: me)?|what can i ask(?: you)?|what should i ask(?: you)?"
                 r"|what (?:kind of |sort of )?questions (?:can|could|should) i ask(?: you)?"
                 r"|what are your (?:capabilities|features|skills))\W*$")
PERSONAL_RE = _c(r"\b(?:marriage|married|marry|wife|husband|spouse|girlfriend|boyfriend|dating|divorce"
                 r"|relationship advice|love life|break ?up|wedding|my (?:family|kids|children|parents|mom|dad"
                 r"|mother|father|son|daughter)|lonely|depress\w*|therapy|horoscope)\b")

GREETING = ("Hi! I'm the MarketingIQ AI Analyst. Ask me about your campaign data, for example "
            "\"Show revenue by platform\" or \"Is January revenue increasing over time?\".")
THANKS = "Glad to help! What would you like to look at next?"
IDENTITY = ("I'm the MarketingIQ AI Analyst. I can analyze your campaign data, compare performance, investigate "
            "trends, apply filters, answer follow-up questions and create charts from your data. For example: "
            "\"Which platform has the highest ROAS?\", \"Compare TikTok and Google Ads revenue\" or "
            "\"Show monthly spend as a line chart\".")
PERSONAL = ("I'm sorry, I can't help with that. I'm MarketingIQ's analyst, so I only work with the campaign "
            "dataset. I'd be glad to help with a question like \"Which platform has the best ROAS?\".")


def small_talk(question: str):
    """(kind, reply) for greetings, thanks, "who are you" and personal off-topic messages; else None."""
    text = question.strip()
    if GREETING_RE.match(text):
        return "greeting", GREETING
    if THANKS_RE.match(text):
        return "thanks", THANKS
    if IDENTITY_RE.match(text):
        return "identity", IDENTITY
    if PERSONAL_RE.search(text) and not qr._has_data_vocab(qr._parse(text, qr._get_entity_index())):
        return "personal", PERSONAL
    return None


# ---------------------------------------------------------------------------
# Follow-up resolution
# ---------------------------------------------------------------------------

REFERENCE_RE = _c(r"\b(?:this|that|those|these|it|its|them|same|again|instead|previous|above|earlier)\b")
LEAD_RE = _c(r"^\W*(?:and|also|now|then|so|ok(?:ay)?|what about|how about|what if|make|turn|convert|change|switch"
             r"|use|try|redo|show (?:it|that|this|them|the same|me that))\b")
COMPARE_CUE_RE = _c(r"\b(?:compare|comparison|vs\.?|versus|against|with|and)\b")
WHY_RE = _c(r"^\W*(?:why|how come|explain(?: (?:this|that|it|why))?|what explains (?:this|that|it)"
            r"|what(?:'s| is) (?:driving|behind) (?:this|that|it)|why (?:is|was|did|does) (?:that|this|it)"
            r"(?: so| the case| happen)?)\W*$")
CHART_WORD_RE = _c(r"\b(?:charts?|graphs?|plot|visuali[sz]\w*|diagram|pie|donut|bars?|lines?|columns?)\b")
MONTH_NUMBERS = {"jan": 1, "feb": 2, "mar": 3, "apr": 4, "may": 5, "jun": 6, "jul": 7, "aug": 8, "sep": 9,
                 "oct": 10, "nov": 11, "dec": 12}
MONTH_WORD_RE = _c(r"\b(january|february|march|april|june|july|august|september|october|november|december"
                   r"|jan|feb|mar|apr|jun|jul|aug|sept?|oct|nov|dec)\b|\b(?:about|for|in|of)\s+(may)\b")
YEAR_WORD_RE = re.compile(r"\b(20\d{2})\b")

NO_CONTEXT_CHART = ("What would you like me to chart? There's no earlier result in this conversation yet. "
                    "For example: \"Chart revenue by platform\" or \"Show monthly spend as a line chart\".")
NO_CONTEXT = ("I don't have an earlier result in this conversation to refer to. What would you like to look at? "
              "For example: \"Revenue by platform\" or \"Monthly spend for TikTok\".")
WHY_NO_CONTEXT = "What would you like me to explain? Ask a question about the data first, then ask why."


@dataclass
class Resolution:
    kind: str                   # none / plan / clarify / planner / why
    plan: qp.Plan = None
    message: str = None
    notes: list = field(default_factory=list)


def _requested_type(text: str):
    if re.search(r"\b(?:pie|donut|doughnut)\b", text):
        return "pie"
    if re.search(r"\b(?:bars?|columns?)\b", text):
        return "bar"
    if re.search(r"\blines?\b", text):
        return "line"
    return None


def _months(text: str) -> list:
    return sorted({MONTH_NUMBERS[(m.group(1) or m.group(2))[:3]] for m in MONTH_WORD_RE.finditer(text)})


def _choose_chart(plan: qp.Plan, requested):
    """(chart type, note) from the result's shape; (None, message) when there's nothing to chart."""
    if plan.intent == "total":
        return None, ("That result is a single figure, so there's nothing to chart. Would you like it by month "
                      "(\"monthly revenue\") or broken down (\"revenue by platform\")?")
    if plan.intent == "change_ranking":
        return None, "Change rankings are shown as text. Ask for the metric by year or by month to chart it."
    if plan.intent == "trend":
        return requested or "line", None
    if plan.intent == "campaign_list" and requested in ("pie", "line"):
        return "bar", "Shown as a bar chart: individual campaigns aren't parts of one whole."
    return requested or "bar", None


def resolve(question: str, state: SessionState) -> Resolution:
    """Deterministic: is this a follow-up, and if so, what complete request does it mean?"""
    text = " ".join(question.lower().split())
    has_plan = state is not None and state.plan is not None
    if WHY_RE.match(text):
        return Resolution("why") if has_plan else Resolution("clarify", message=WHY_NO_CONTEXT)
    f = qr._parse(question, qr._get_entity_index())
    metrics = [m for m in qr._metric_names(f) if m in qp.METRICS]
    chart_req = bool(CHART_WORD_RE.search(text))
    months, years = _months(text), sorted({int(y) for y in YEAR_WORD_RE.findall(text)})
    ref, lead = REFERENCE_RE.search(text), LEAD_RE.search(text)
    short = len(text.split()) <= 6
    if not (ref or lead or (not metrics and short and (f.entities or f.dimensions or months or years or chart_req))):
        return Resolution("none")
    self_contained = metrics and not ref and (f.dimensions or qr.TOTALS_RE.search(text) or qr.TREND_RE.search(text)
                                              or len(f.entities) >= 2 or qr.CAMPAIGN_RE.search(text))
    if self_contained:
        return Resolution("none")
    if not has_plan:
        if (ref or chart_req) and not metrics:
            return Resolution("clarify", message=NO_CONTEXT_CHART if chart_req else NO_CONTEXT)
        return Resolution("none")

    prev = state.plan
    new = copy.deepcopy(prev)
    new.visualization, new.notes = None, []
    changed, notes = False, []

    if metrics:
        new.metrics, changed = metrics[:qp.MAX_METRICS], True

    ents = [(d, v) for d, v in f.entities if d in qp.FILTER_DIMENSIONS]
    if ents:
        d = ents[0][0]
        vals = [v for dd, v in ents if dd == d]
        key = qr.ENTITY_FILTER_KEYS[d]
        focus_compare = prev.intent == "compare_entities" and prev.dimension == d
        if len(vals) >= 2:
            new.intent, new.dimension, new.entities = "compare_entities", d, vals
            new.filters.pop(key, None)
        elif COMPARE_CUE_RE.search(text) and (prev.filters.get(key) or focus_compare):
            base = prev.entities if focus_compare else [prev.filters[key]]
            new.intent, new.dimension, new.entities = "compare_entities", d, list(dict.fromkeys(base + vals))
            new.filters.pop(key, None)
        elif re.search(r"\b(?:compare|vs\.?|versus|against)\b", text):
            return Resolution("clarify", message=f"What should I compare {vals[0]} with?")
        else:
            new.filters[key] = vals[0]
            if new.dimension == d and new.intent in ("breakdown", "change_ranking", "compare_entities"):
                new.intent, new.dimension, new.entities = "total", None, []
        for dd, v in ents:
            if dd != d:
                new.filters[qr.ENTITY_FILTER_KEYS[dd]] = v
        changed = True

    named = {d for d, _ in f.entities}
    dims = [d for d in f.dimensions if d not in named]
    if dims:
        new.dimension = dims[0]
        new.filters.pop(qr.ENTITY_FILTER_KEYS.get(dims[0]), None)
        if new.intent not in ("breakdown", "change_ranking"):
            new.intent, new.entities = "breakdown", []
        changed = True

    if months or years:
        if new.intent == "period_comparison":
            new.months = months or new.months
            new.years = years or new.years
            if months and len(years) == 1:
                new.intent, new.grain = "total", None
        elif new.intent == "trend" and months and not years:
            new.intent, new.months, new.years, new.grain = "period_comparison", months, [], "year"
        else:
            new.years = years or new.years
            new.months = months or ([] if years else new.months)
            if new.intent == "trend" and months:
                new.intent, new.grain = "total", None
        changed = True

    if chart_req:
        kind, note = _choose_chart(new, _requested_type(text))
        if kind is None:
            return Resolution("clarify", message=note)
        new.visualization = kind
        if note:
            notes.append(note)
        changed = True
    elif prev.visualization and changed:
        # The previous answer was a chart: keep charting while the result can be charted ("now spend").
        keep = prev.visualization if prev.visualization == "pie" and new.intent == "breakdown" else None
        new.visualization = _choose_chart(new, keep)[0] if new.intent not in ("total", "change_ranking") else None

    if not changed:
        return Resolution("planner", plan=prev)
    try:
        checked = qp.validate_plan(json.dumps(qp.plan_to_raw(new)))
    except qp.PlanError as e:
        return Resolution("clarify", message=e.public)
    return Resolution("plan", plan=checked, notes=notes)  # execute_plan adds checked.notes itself


def describe(plan: qp.Plan) -> str:
    """The remembered request in words, for "why?" follow-ups (answered by the explanation path)."""
    parts = [" and ".join(cb._label(m) for m in plan.metrics)]
    if plan.dimension:
        parts.append("by " + plan.dimension.replace("_", " "))
    if plan.entities:
        parts.append("for " + " and ".join(plan.entities))
    parts += [f"for {v}" for v in plan.filters.values()]
    if plan.months:
        names = [qp.calendar.month_name[m] for m in plan.months]
        parts.append("in " + (names[0] if len(names) == 1 else f"{names[0]} to {names[-1]}"))
    if plan.years:
        parts.append("in " + " and ".join(map(str, plan.years)))
    if plan.intent in ("trend", "period_comparison", "change_ranking"):
        parts.append("over time")
    return " ".join(parts)


# ---------------------------------------------------------------------------
# Plans behind the other answer paths (what a later follow-up edits)
# ---------------------------------------------------------------------------

DEFAULT_METRICS = ["revenue", "spend", "roas"]


def plan_from_router(r: dict):
    """The DIRECT_DATABASE answer as a plan, or None for answers a follow-up can't build on."""
    tool, inp = r.get("tool"), r.get("tool_input") or {}
    focus = [m for m in r.get("focus_metrics") or [] if m in qp.METRICS][:qp.MAX_METRICS]
    scope = dict(r.get("scope") or {})
    period = r.get("period")
    raw = {"intent": None, "metrics": focus or DEFAULT_METRICS, "dimension": None, "entities": [], "filters": scope,
           "months": [int(period[5:7])] if period and len(period) == 7 else [],
           "years": [int(period[:4])] if period else [], "grain": None, "conditions": [], "order": "desc",
           "limit": None, "visualization": None}
    if tool == "get_totals":
        raw["intent"] = "total"
    elif tool == "rank_dimension" and inp.get("metric") in qp.METRICS:
        raw.update(intent="breakdown", metrics=[inp["metric"]], dimension=inp["dimension"], order=inp.get("order", "desc"),
                   limit=None if inp.get("limit") in (1, 10) else inp.get("limit"))
    elif tool == "trend_over_time":
        raw.update(intent="trend", metrics=[inp.get("metric", "revenue")], grain="month")
    elif tool == "compare_entities":
        raw.update(intent="compare_entities", dimension=inp["dimension"], entities=list(inp["names"]))
    elif tool == "get_entity_metrics" and inp.get("dimension") in qr.ENTITY_FILTER_KEYS:
        raw.update(intent="total", filters={**scope, qr.ENTITY_FILTER_KEYS[inp["dimension"]]: inp["name"]})
    elif tool == "filter_campaigns":
        sort_by = inp.get("sort_by", "profit")
        raw.update(intent="campaign_list", metrics=[sort_by] if sort_by in qp.METRICS else ["profit"],
                   conditions=list(inp.get("conditions") or []), order=inp.get("order", "asc"), limit=inp.get("limit"))
    else:
        return None
    return checked_plan(raw)


def checked_plan(fields: dict):
    """Plan fields -> a validated Plan (dataset spellings, allowlists), or None."""
    try:
        plan = qp.Plan(**{k: v for k, v in fields.items() if k in qp.Plan.__dataclass_fields__})
        return qp.validate_plan(json.dumps(qp.plan_to_raw(plan)))
    except (qp.PlanError, TypeError, KeyError, ValueError):
        return None
